### ISSUE TITLE
iosxr_interface

### ISSUE THREAD

**Issue by rjoensen** [netascode/terraform-provider-iosxr#105]
Hi there,

There seems to be missing something in the destroying part of removing an interface configuration using iosxr_interface. Creating it is just fine, but when you destroy (remove the resource reference from your .tf file) it does not remove the configuration from the IOS-XR device.

**Comment by danischm** [comment]
Indeed, which is due to the gNMI/YANG interface we are using, where we cannot simply remove a full interface configuration.  For most of the other resources this works, but there are a few exceptions like `iosxr_interface`.

**Comment by rjoensen** [comment]
Thank you for a quick update on this. I will try to think of a workaround to blanket interface configs out instead of destroying.

**Comment by danischm** [comment]
Yeah, if you replace the attribute values with empty strings and default values, then run a "terraform apply" it should more or less revert the interface config.
